language: node_js
node_js:
- 10.14.1
branches:
  except:
  - "/^[0-9]/"
env:
  matrix:
  global:
cache: bundler
addons:
  hosts:
  - 127.0.0.1 sonarqube.service.redmart.com
before_install:
- '/usr/bin/curl -o travis-entry-point.sh --header "Authorization: token $GITHUB_TOKEN" --header "Accept: application/vnd.github.v3.raw" --fail --silent --show-error --location https://api.github.com/repos/redmart/devops-tool/contents/travis-entry-point.sh && . ./travis-entry-point.sh'
- nvm install 10.14.1
- nvm install 0.10.33
install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- nvm use 10.14.1
- npm install
- nvm use 0.10.33
- npm install -g grunt@0.4.1 grunt-cli@0.1.9
- redmart_install
- gem install bundler;
- bundle install
before_script:
- redmart_before_script
- redmart_tunnel -l 4444:selenium.alpha.redmart.com:4444
script:
- nvm use 0.10.33
- cd ci/; npm install; chmod +x rm_version_mgr.sh ; ./rm_version_mgr.sh ; cd ../
- nvm use 10.14.1
- chmod +x build_app.sh ; ./build_app.sh npm
- cucumber -S --retry 1 -p ci --guess --tags @selfService
- export PROFILE="mobile'
- cucumber -S --retry 1 -p ci --guess --tags @selfServiceMob
after_success:
- nvm use 0.10.33
- cd ci/; chmod +x rm_deploy.sh ; ./rm_deploy.sh ; cd ../
- redmart_after_success
after_failure:
- echo "ERROR ********* Travis build failed. Please check the travis logs for details.
  **********"
after_script:
- redmart_after_script
notifications:
  email:
    on_success: never
